DROP TABLE IF EXISTS ranking;

CREATE TABLE ranking (
	id INT NOT NULL AUTO_INCREMENT,
	jogador INT NOT NULL,
	fase INT NOT NULL,
	tempo BIGINT NOT NULL,
	data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

